### ISSUE TITLE
server

### ISSUE THREAD

**Issue by kappithannemo** [CW4RR10R/Auto-Responder-for-WA-Plugin-Python#8]
Hi Arun bro,
how are we supposed to run the server? Termux?
Is it possible to deploy it in heroku?
please respond....

**Comment by arunpt** [comment]
@kappithannemo Ofc you can run this on termux and heroku as well, just add a Procfile if you're trying to deploy on heroku

**Comment by kappithannemo** [comment]
i am a noob.
i understand procfile is the set of commands that is supposed to run in heroku at the app starting.
but i donno what all should be the contents.
It would be so nice of you if you share more details or perhaps if you are free, add a procfile to this yourself if its a simple task.
anyways, thanks for responding

**Comment by kappithannemo** [comment]
hi bro, i did a procfile and while creating the app in heroku, in the
 Run scripts & scale dynos section while building i am getting an error like this: error scaling dynos: Couldn't find that process type (worker). 

i added a procfile and app.json and its not working. please suggest solution.

https://github.com/kappithannemo/plugin-resp/blob/master/Procfile has the procfile i managed to create.

**Comment by arunpt** [comment]
> hi bro, i did a procfile and while creating the app in heroku, in the
> Run scripts & scale dynos section while building i am getting an error like this: error scaling dynos: Couldn't find that process type (worker).
> 
> i added a procfile and app.json and its not working. please suggest solution.
> 
> https://github.com/kappithannemo/plugin-resp/blob/master/Procfile has the procfile i managed to create.

Try ```web: gunicorn main:app``` and make sure you've added gunicorn in your requirements.txt

**Comment by kappithannemo** [comment]
Greetings bro,

still the same error ; "error scaling dynos: Couldn't find that process type (worker)."

i have added an app.json file as well before, maybe the error is because of something in that
https://github.com/kappithannemo/plugin-resp/blob/master/app.json  has the app.json file.

**Comment by arunpt** [comment]
> Greetings bro,
> 
> still the same error ; "error scaling dynos: Couldn't find that process type (worker)."
> 
> i have added an app.json file as well before, maybe the error is because of something in that
> https://github.com/kappithannemo/plugin-resp/blob/master/app.json has the app.json file.

app.json is not mandatory for deploying apps to heroku.You just want to add a  Procfile and runtime.txt (if required) , then create a heroku app and connect your GitHub repo and hit deploy, thats it
